#!/usr/bin/env bash
# Table 1 — HUQ-SATMD, Llama-3.1-8B
#
# Set HF_HUB_TOKEN in your environment before running if models are gated.

set -e
PYTHON="${PYTHON:-python}"

COMMON=(
  ignore_exceptions=False
  use_density_based_ue=True
  batch_size=1
  subsample_eval_dataset=2000
  subsample_background_train_dataset=1
  model.path=meta-llama/Meta-Llama-3.1-8B
  +model.attn_implementation=eager
  '+metric_thrs=[0.3]'
  '+layers=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,-1]'
  +clean_md_device=cuda
  +loadin4bit=False
  +method=huq_satmd
  +token_aggregation=average
  +pre_compile_features=True
)

# ─── ID ──────────────────────────────────────────────────────────────────────

HYDRA_CONFIG=configs/polygraph_eval_sciq.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800
HYDRA_CONFIG=configs/polygraph_eval_triviaqa.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800
HYDRA_CONFIG=configs/polygraph_eval_coqa.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800
HYDRA_CONFIG=configs/polygraph_eval_pubmedqa.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800
HYDRA_CONFIG=configs/polygraph_eval_xsum.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800
HYDRA_CONFIG=configs/polygraph_eval_cnn.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800

# ─── LOO ─────────────────────────────────────────────────────────────────────

# SciQ LOO
HYDRA_CONFIG=configs/polygraph_eval_sciq.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=200 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train' \
  +train_dataset_4='coqa' +max_new_tokens_4=20 +train_text_column_4='questions' +train_label_column_4='answers' +train_prompt_4='\n\nQuestion: \{question\}\nAnswer:\{answer\}' +train_split_4='train' +train_description_4='The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: \{story\}' \
  +train_dataset_5='['trivia_qa', 'rc.nocontext']' +max_new_tokens_5=20 +train_text_column_5='question' +train_label_column_5='answer' +train_prompt_5='Question: \{question\}\nAnswer:\{answer\}' +train_split_5='train' +few_shot_split_5='train' +train_n_shot_5=5 \
  +train_dataset_6='['cais/mmlu', 'all']' +max_new_tokens_6=3 +train_text_column_6='question' +train_label_column_6='answer' +train_prompt_6='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_6='validation' +train_description_6='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_6='dev' +train_n_shot_6=5 \
  +train_dataset_7='['truthful_qa', 'generation']' +max_new_tokens_7=128 +train_text_column_7='question' +train_label_column_7='correct_answers' +train_prompt_7='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_7='validation' +few_shot_split_7='validation' +train_n_shot_7=0 \
  +train_dataset_8='bigbio/pubmed_qa' +max_new_tokens_8=128 +train_text_column_8='QUESTION' +train_label_column_8='LONG_ANSWER' +train_prompt_8='The following are abstract and question about them. Each abstract is followed by a question and answer to a given question. Abstract: \{context\}\nQuestion: \{question\}\nAnswer:' +train_split_8='train' +train_n_shot_8=0 \
  +train_dataset_9='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_9=128 +train_text_column_9='Question' +train_label_column_9='Answer' +train_prompt_9='Question: \{question\}\nAnswer: \{answer\}' +train_split_9='train' +few_shot_split_9='train' +train_n_shot_9=5

# TriviaQA LOO
HYDRA_CONFIG=configs/polygraph_eval_triviaqa.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=200 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train' \
  +train_dataset_4='coqa' +max_new_tokens_4=20 +train_text_column_4='questions' +train_label_column_4='answers' +train_prompt_4='\n\nQuestion: \{question\}\nAnswer:\{answer\}' +train_split_4='train' +train_description_4='The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: \{story\}' \
  +train_dataset_5='['cais/mmlu', 'all']' +max_new_tokens_5=3 +train_text_column_5='question' +train_label_column_5='answer' +train_prompt_5='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_5='validation' +train_description_5='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_5='dev' +train_n_shot_5=5 \
  +train_dataset_6='['truthful_qa', 'generation']' +max_new_tokens_6=128 +train_text_column_6='question' +train_label_column_6='correct_answers' +train_prompt_6='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_6='validation' +few_shot_split_6='validation' +train_n_shot_6=0 \
  +train_dataset_7='bigbio/pubmed_qa' +max_new_tokens_7=128 +train_text_column_7='QUESTION' +train_label_column_7='LONG_ANSWER' +train_prompt_7='The following are abstract and question about them. Each abstract is followed by a question and answer to a given question. Abstract: \{context\}\nQuestion: \{question\}\nAnswer:' +train_split_7='train' +train_n_shot_7=0 \
  +train_dataset_8='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_8=128 +train_text_column_8='Question' +train_label_column_8='Answer' +train_prompt_8='Question: \{question\}\nAnswer: \{answer\}' +train_split_8='train' +few_shot_split_8='train' +train_n_shot_8=5 \
  +train_dataset_9='sciq' +max_new_tokens_9=20 +train_text_column_9='question' +train_label_column_9='correct_answer' +train_prompt_9='\n\nQuestion: \{question\}\nAnswer:' +train_split_9='train' +train_description_9='The following are context and question about them. Each context is followed by a question and answer to a given question.\n\nContext: \{context\}'

# CoQA LOO
HYDRA_CONFIG=configs/polygraph_eval_coqa.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=200 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train' \
  +train_dataset_4='['trivia_qa', 'rc.nocontext']' +max_new_tokens_4=20 +train_text_column_4='question' +train_label_column_4='answer' +train_prompt_4='Question: \{question\}\nAnswer:\{answer\}' +train_split_4='train' +few_shot_split_4='train' +train_n_shot_4=5 \
  +train_dataset_5='['cais/mmlu', 'all']' +max_new_tokens_5=3 +train_text_column_5='question' +train_label_column_5='answer' +train_prompt_5='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_5='validation' +train_description_5='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_5='dev' +train_n_shot_5=5 \
  +train_dataset_6='['truthful_qa', 'generation']' +max_new_tokens_6=128 +train_text_column_6='question' +train_label_column_6='correct_answers' +train_prompt_6='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_6='validation' +few_shot_split_6='validation' +train_n_shot_6=0 \
  +train_dataset_7='bigbio/pubmed_qa' +max_new_tokens_7=128 +train_text_column_7='QUESTION' +train_label_column_7='LONG_ANSWER' +train_prompt_7='The following are abstract and question about them. Each abstract is followed by a question and answer to a given question. Abstract: \{context\}\nQuestion: \{question\}\nAnswer:' +train_split_7='train' +train_n_shot_7=0 \
  +train_dataset_8='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_8=128 +train_text_column_8='Question' +train_label_column_8='Answer' +train_prompt_8='Question: \{question\}\nAnswer: \{answer\}' +train_split_8='train' +few_shot_split_8='train' +train_n_shot_8=5 \
  +train_dataset_9='sciq' +max_new_tokens_9=20 +train_text_column_9='question' +train_label_column_9='correct_answer' +train_prompt_9='\n\nQuestion: \{question\}\nAnswer:' +train_split_9='train' +train_description_9='The following are context and question about them. Each context is followed by a question and answer to a given question.\n\nContext: \{context\}'

# PubmedQA LOO
HYDRA_CONFIG=configs/polygraph_eval_pubmedqa.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=200 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train' \
  +train_dataset_4='coqa' +max_new_tokens_4=20 +train_text_column_4='questions' +train_label_column_4='answers' +train_prompt_4='\n\nQuestion: \{question\}\nAnswer:\{answer\}' +train_split_4='train' +train_description_4='The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: \{story\}' \
  +train_dataset_5='['trivia_qa', 'rc.nocontext']' +max_new_tokens_5=20 +train_text_column_5='question' +train_label_column_5='answer' +train_prompt_5='Question: \{question\}\nAnswer:\{answer\}' +train_split_5='train' +few_shot_split_5='train' +train_n_shot_5=5 \
  +train_dataset_6='['cais/mmlu', 'all']' +max_new_tokens_6=3 +train_text_column_6='question' +train_label_column_6='answer' +train_prompt_6='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_6='validation' +train_description_6='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_6='dev' +train_n_shot_6=5 \
  +train_dataset_7='['truthful_qa', 'generation']' +max_new_tokens_7=128 +train_text_column_7='question' +train_label_column_7='correct_answers' +train_prompt_7='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_7='validation' +few_shot_split_7='validation' +train_n_shot_7=0 \
  +train_dataset_8='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_8=128 +train_text_column_8='Question' +train_label_column_8='Answer' +train_prompt_8='Question: How many people are affected by early-onset glaucoma ?\nAnswer: Primary congenital glaucoma affects approximately 1 in 10\,000 people. Its frequency is higher in the Middle East. Juvenile open-angle glaucoma affects about 1 in 50\,000 people. Primary open-angle glaucoma is much more common after the age of 40\, affecting about 1 percent of the population worldwide.\nQuestion: What is the outlook for Von Hippel-Lindau Disease \(VHL\) ?\nAnswer: The prognosis for individuals with VHL depends on then number\, location\, and complications of the tumors. Untreated\, VHL may result in blindness and/or permanent brain damage. With early detection and treatment the prognosis is significantly improved. Death is usually caused by complications of brain tumors or kidney cancer.\nQuestion: How many people are affected by osteopetrosis ?\nAnswer: Autosomal dominant osteopetrosis is the most common form of the disorder\, affecting about 1 in 20\,000 people. Autosomal recessive osteopetrosis is rarer\, occurring in an estimated 1 in 250\,000 people.  Other forms of osteopetrosis are very rare. Only a few cases of intermediate autosomal osteopetrosis and OL-EDA-ID have been reported in the medical literature.\nQuestion: Is Townes-Brocks Syndrome inherited ?\nAnswer: This condition is inherited in an autosomal dominant pattern\, which means one copy of the altered gene in each cell is sufficient to cause the disorder.\nQuestion: What is \(are\) Osteoporosis ?\nAnswer: Osteoporosis is a disease that thins and weakens the bones to the point that they break easily. Women and men with osteoporosis most often break bones in the hip\, spine\, and wrist\, but osteoporosis can be the cause of bone fractures anywhere.\nQuestion: \{question\}\nAnswer: \{answer\}' +train_split_8='train' +train_n_shot_8=0 \
  +train_dataset_9='sciq' +max_new_tokens_9=20 +train_text_column_9='question' +train_label_column_9='correct_answer' +train_prompt_9='\n\nQuestion: \{question\}\nAnswer:' +train_split_9='train' +train_description_9='The following are context and question about them. Each context is followed by a question and answer to a given question.\n\nContext: \{context\}'

# XSum LOO
HYDRA_CONFIG=configs/polygraph_eval_xsum.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=200 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='['cnn_dailymail', '3.0.0']' +max_new_tokens_2=128 +train_text_column_2='article' +train_label_column_2='highlights' +train_prompt_2='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='coqa' +max_new_tokens_3=20 +train_text_column_3='questions' +train_label_column_3='answers' +train_prompt_3='\n\nQuestion: \{question\}\nAnswer:\{answer\}' +train_split_3='train' +train_description_3='The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: \{story\}' \
  +train_dataset_4='['trivia_qa', 'rc.nocontext']' +max_new_tokens_4=20 +train_text_column_4='question' +train_label_column_4='answer' +train_prompt_4='Question: \{question\}\nAnswer:\{answer\}' +train_split_4='train' +few_shot_split_4='train' +train_n_shot_4=5 \
  +train_dataset_5='['cais/mmlu', 'all']' +max_new_tokens_5=3 +train_text_column_5='question' +train_label_column_5='answer' +train_prompt_5='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_5='validation' +train_description_5='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_5='dev' +train_n_shot_5=5 \
  +train_dataset_6='['truthful_qa', 'generation']' +max_new_tokens_6=128 +train_text_column_6='question' +train_label_column_6='correct_answers' +train_prompt_6='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_6='validation' +few_shot_split_6='validation' +train_n_shot_6=0 \
  +train_dataset_7='bigbio/pubmed_qa' +max_new_tokens_7=128 +train_text_column_7='QUESTION' +train_label_column_7='LONG_ANSWER' +train_prompt_7='The following are abstract and question about them. Each abstract is followed by a question and answer to a given question. Abstract: \{context\}\nQuestion: \{question\}\nAnswer:' +train_split_7='train' +train_n_shot_7=0 \
  +train_dataset_8='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_8=128 +train_text_column_8='Question' +train_label_column_8='Answer' +train_prompt_8='Question: \{question\}\nAnswer: \{answer\}' +train_split_8='train' +few_shot_split_8='train' +train_n_shot_8=5 \
  +train_dataset_9='sciq' +max_new_tokens_9=20 +train_text_column_9='question' +train_label_column_9='correct_answer' +train_prompt_9='\n\nQuestion: \{question\}\nAnswer:' +train_split_9='train' +train_description_9='The following are context and question about them. Each context is followed by a question and answer to a given question.\n\nContext: \{context\}'

# CNN LOO
HYDRA_CONFIG=configs/polygraph_eval_cnn.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=200 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='coqa' +max_new_tokens_3=20 +train_text_column_3='questions' +train_label_column_3='answers' +train_prompt_3='\n\nQuestion: \{question\}\nAnswer:\{answer\}' +train_split_3='train' +train_description_3='The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: \{story\}' \
  +train_dataset_4='['trivia_qa', 'rc.nocontext']' +max_new_tokens_4=20 +train_text_column_4='question' +train_label_column_4='answer' +train_prompt_4='Question: \{question\}\nAnswer:\{answer\}' +train_split_4='train' +few_shot_split_4='train' +train_n_shot_4=5 \
  +train_dataset_5='['cais/mmlu', 'all']' +max_new_tokens_5=3 +train_text_column_5='question' +train_label_column_5='answer' +train_prompt_5='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_5='validation' +train_description_5='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_5='dev' +train_n_shot_5=5 \
  +train_dataset_6='['truthful_qa', 'generation']' +max_new_tokens_6=128 +train_text_column_6='question' +train_label_column_6='correct_answers' +train_prompt_6='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_6='validation' +few_shot_split_6='validation' +train_n_shot_6=0 \
  +train_dataset_7='bigbio/pubmed_qa' +max_new_tokens_7=128 +train_text_column_7='QUESTION' +train_label_column_7='LONG_ANSWER' +train_prompt_7='The following are abstract and question about them. Each abstract is followed by a question and answer to a given question. Abstract: \{context\}\nQuestion: \{question\}\nAnswer:' +train_split_7='train' +train_n_shot_7=0 \
  +train_dataset_8='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_8=128 +train_text_column_8='Question' +train_label_column_8='Answer' +train_prompt_8='Question: \{question\}\nAnswer: \{answer\}' +train_split_8='train' +few_shot_split_8='train' +train_n_shot_8=5 \
  +train_dataset_9='sciq' +max_new_tokens_9=20 +train_text_column_9='question' +train_label_column_9='correct_answer' +train_prompt_9='\n\nQuestion: \{question\}\nAnswer:' +train_split_9='train' +train_description_9='The following are context and question about them. Each context is followed by a question and answer to a given question.\n\nContext: \{context\}'

# ─── 1D-SameTask ─────────────────────────────────────────────────────────────

HYDRA_CONFIG=configs/polygraph_eval_sciq.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_1=128 +train_text_column_1='Question' +train_label_column_1='Answer' +train_prompt_1='Question: \{question\}\nAnswer: \{answer\}' +train_split_1='train' +few_shot_split_1='train' +train_n_shot_1=5

HYDRA_CONFIG=configs/polygraph_eval_triviaqa.yaml  $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_1=128 +train_text_column_1='Question' +train_label_column_1='Answer' +train_prompt_1='Question: \{question\}\nAnswer: \{answer\}' +train_split_1='train' +few_shot_split_1='train' +train_n_shot_1=5

HYDRA_CONFIG=configs/polygraph_eval_coqa.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_1=128 +train_text_column_1='Question' +train_label_column_1='Answer' +train_prompt_1='Question: \{question\}\nAnswer: \{answer\}' +train_split_1='train' +few_shot_split_1='train' +train_n_shot_1=5

HYDRA_CONFIG=configs/polygraph_eval_pubmedqa.yaml  $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_1=128 +train_text_column_1='Question' +train_label_column_1='Answer' +train_prompt_1='Question: \{question\}\nAnswer: \{answer\}' +train_split_1='train' +few_shot_split_1='train' +train_n_shot_1=5

HYDRA_CONFIG=configs/polygraph_eval_xsum.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train'

HYDRA_CONFIG=configs/polygraph_eval_cnn.yaml       $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train'

# ─── DiffTask ────────────────────────────────────────────────────────────────
HYDRA_CONFIG=configs/polygraph_eval_sciq.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=600 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train'

HYDRA_CONFIG=configs/polygraph_eval_triviaqa.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=600 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train'

HYDRA_CONFIG=configs/polygraph_eval_coqa.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=600 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train'

HYDRA_CONFIG=configs/polygraph_eval_pubmedqa.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=600 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train' \
  +train_dataset_2='xsum' +max_new_tokens_2=56 +train_text_column_2='document' +train_label_column_2='summary' +train_prompt_2='Here is the text and it is short one-sentence summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_2='train' \
  +train_dataset_3='['cnn_dailymail', '3.0.0']' +max_new_tokens_3=128 +train_text_column_3='article' +train_label_column_3='highlights' +train_prompt_3='Here is the text and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_3='train'

HYDRA_CONFIG=configs/polygraph_eval_xsum.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=300 \
  +train_dataset_1='coqa' +max_new_tokens_1=20 +train_text_column_1='questions' +train_label_column_1='answers' +train_prompt_1='\n\nQuestion: \{question\}\nAnswer:\{answer\}' +train_split_1='train' +train_description_1='The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: \{story\}' \
  +train_dataset_2='['trivia_qa', 'rc.nocontext']' +max_new_tokens_2=20 +train_text_column_2='question' +train_label_column_2='answer' +train_prompt_2='Question: \{question\}\nAnswer:\{answer\}' +train_split_2='train' +few_shot_split_2='train' +train_n_shot_2=5 \
  +train_dataset_3='['cais/mmlu', 'all']' +max_new_tokens_3=3 +train_text_column_3='question' +train_label_column_3='answer' +train_prompt_3='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_3='validation' +train_description_3='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_3='dev' +train_n_shot_3=5 \
  +train_dataset_4='['truthful_qa', 'generation']' +max_new_tokens_4=128 +train_text_column_4='question' +train_label_column_4='correct_answers' +train_prompt_4='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_4='validation' +few_shot_split_4='validation' +train_n_shot_4=0 \
  +train_dataset_5='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_5=128 +train_text_column_5='Question' +train_label_column_5='Answer' +train_prompt_5='Question: How many people are affected by early-onset glaucoma ?\nAnswer: Primary congenital glaucoma affects approximately 1 in 10\,000 people. Its frequency is higher in the Middle East. Juvenile open-angle glaucoma affects about 1 in 50\,000 people. Primary open-angle glaucoma is much more common after the age of 40\, affecting about 1 percent of the population worldwide.\nQuestion: What is the outlook for Von Hippel-Lindau Disease \(VHL\) ?\nAnswer: The prognosis for individuals with VHL depends on then number\, location\, and complications of the tumors. Untreated\, VHL may result in blindness and/or permanent brain damage. With early detection and treatment the prognosis is significantly improved. Death is usually caused by complications of brain tumors or kidney cancer.\nQuestion: How many people are affected by osteopetrosis ?\nAnswer: Autosomal dominant osteopetrosis is the most common form of the disorder\, affecting about 1 in 20\,000 people. Autosomal recessive osteopetrosis is rarer\, occurring in an estimated 1 in 250\,000 people.  Other forms of osteopetrosis are very rare. Only a few cases of intermediate autosomal osteopetrosis and OL-EDA-ID have been reported in the medical literature.\nQuestion: Is Townes-Brocks Syndrome inherited ?\nAnswer: This condition is inherited in an autosomal dominant pattern\, which means one copy of the altered gene in each cell is sufficient to cause the disorder.\nQuestion: What is \(are\) Osteoporosis ?\nAnswer: Osteoporosis is a disease that thins and weakens the bones to the point that they break easily. Women and men with osteoporosis most often break bones in the hip\, spine\, and wrist\, but osteoporosis can be the cause of bone fractures anywhere.\nQuestion: \{question\}\nAnswer: \{answer\}' +train_split_5='train' +train_n_shot_5=0 \
  +train_dataset_6='sciq' +max_new_tokens_6=20 +train_text_column_6='question' +train_label_column_6='correct_answer' +train_prompt_6='\n\nQuestion: \{question\}\nAnswer:' +train_split_6='train' +train_description_6='The following are context and question about them. Each context is followed by a question and answer to a given question.\n\nContext: \{context\}'

HYDRA_CONFIG=configs/polygraph_eval_cnn.yaml $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=300 \
  +train_dataset_1='coqa' +max_new_tokens_1=20 +train_text_column_1='questions' +train_label_column_1='answers' +train_prompt_1='\n\nQuestion: \{question\}\nAnswer:\{answer\}' +train_split_1='train' +train_description_1='The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: \{story\}' \
  +train_dataset_2='['trivia_qa', 'rc.nocontext']' +max_new_tokens_2=20 +train_text_column_2='question' +train_label_column_2='answer' +train_prompt_2='Question: \{question\}\nAnswer:\{answer\}' +train_split_2='train' +few_shot_split_2='train' +train_n_shot_2=5 \
  +train_dataset_3='['cais/mmlu', 'all']' +max_new_tokens_3=3 +train_text_column_3='question' +train_label_column_3='answer' +train_prompt_3='\nQ:\{question\}\nA. \{choices\[0\]\}\nB. \{choices\[1\]\}\nC. \{choices\[2\]\}\nD. \{choices\[3\]\}\nAnswer:\{answer\}' +train_split_3='validation' +train_description_3='The following are multiple choice questions \(with answers\) about \{subject\}.\n' +few_shot_split_3='dev' +train_n_shot_3=5 \
  +train_dataset_4='['truthful_qa', 'generation']' +max_new_tokens_4=128 +train_text_column_4='question' +train_label_column_4='correct_answers' +train_prompt_4='Q: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: I have no comment.\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona\, Spain.\n\nQ:\{question\}\nA:' +train_split_4='validation' +few_shot_split_4='validation' +train_n_shot_4=0 \
  +train_dataset_5='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_5=128 +train_text_column_5='Question' +train_label_column_5='Answer' +train_prompt_5='Question: How many people are affected by early-onset glaucoma ?\nAnswer: Primary congenital glaucoma affects approximately 1 in 10\,000 people. Its frequency is higher in the Middle East. Juvenile open-angle glaucoma affects about 1 in 50\,000 people. Primary open-angle glaucoma is much more common after the age of 40\, affecting about 1 percent of the population worldwide.\nQuestion: What is the outlook for Von Hippel-Lindau Disease \(VHL\) ?\nAnswer: The prognosis for individuals with VHL depends on then number\, location\, and complications of the tumors. Untreated\, VHL may result in blindness and/or permanent brain damage. With early detection and treatment the prognosis is significantly improved. Death is usually caused by complications of brain tumors or kidney cancer.\nQuestion: How many people are affected by osteopetrosis ?\nAnswer: Autosomal dominant osteopetrosis is the most common form of the disorder\, affecting about 1 in 20\,000 people. Autosomal recessive osteopetrosis is rarer\, occurring in an estimated 1 in 250\,000 people.  Other forms of osteopetrosis are very rare. Only a few cases of intermediate autosomal osteopetrosis and OL-EDA-ID have been reported in the medical literature.\nQuestion: Is Townes-Brocks Syndrome inherited ?\nAnswer: This condition is inherited in an autosomal dominant pattern\, which means one copy of the altered gene in each cell is sufficient to cause the disorder.\nQuestion: What is \(are\) Osteoporosis ?\nAnswer: Osteoporosis is a disease that thins and weakens the bones to the point that they break easily. Women and men with osteoporosis most often break bones in the hip\, spine\, and wrist\, but osteoporosis can be the cause of bone fractures anywhere.\nQuestion: \{question\}\nAnswer: \{answer\}' +train_split_5='train' +train_n_shot_5=0 \
  +train_dataset_6='sciq' +max_new_tokens_6=20 +train_text_column_6='question' +train_label_column_6='correct_answer' +train_prompt_6='\n\nQuestion: \{question\}\nAnswer:' +train_split_6='train' +train_description_6='The following are context and question about them. Each context is followed by a question and answer to a given question.\n\nContext: \{context\}'

# ─── 1D-DiffTask ─────────────────────────────────────────────────────────────

HYDRA_CONFIG=configs/polygraph_eval_sciq.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train'

HYDRA_CONFIG=configs/polygraph_eval_triviaqa.yaml  $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train'

HYDRA_CONFIG=configs/polygraph_eval_coqa.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train'

HYDRA_CONFIG=configs/polygraph_eval_pubmedqa.yaml  $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='knkarthick/samsum' +max_new_tokens_1=128 +train_text_column_1='dialogue' +train_label_column_1='summary' +train_prompt_1='Here is the dialogue and it is short summary.\n\nText:\n\{text\}\n\nSummary \(one sentence\):\n' +train_split_1='train'

HYDRA_CONFIG=configs/polygraph_eval_xsum.yaml      $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_1=128 +train_text_column_1='Question' +train_label_column_1='Answer' +train_prompt_1='Question: \{question\}\nAnswer: \{answer\}' +train_split_1='train' +few_shot_split_1='train' +train_n_shot_1=5

HYDRA_CONFIG=configs/polygraph_eval_cnn.yaml       $PYTHON run_polygraph.py "${COMMON[@]}" subsample_train_dataset=1800 \
  +train_dataset_1='keivalya/MedQuad-MedicalQnADataset' +max_new_tokens_1=128 +train_text_column_1='Question' +train_label_column_1='Answer' +train_prompt_1='Question: \{question\}\nAnswer: \{answer\}' +train_split_1='train' +few_shot_split_1='train' +train_n_shot_1=5
